spring.application.name=Steem
spring.datasource.url=jdbc:mariadb://localhost:3306/steemdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
openai.api.key=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
openai.model=tngtech/deepseek-r1t2-chimera:free

